### ISSUE TITLE
Tarry Spots Sometimes Disappear and Reappear

### ISSUE THREAD

**Issue by DougLefelhocz** [twohoursonelife/OldOneLifeData7#1]

**Comment by connorhsm** [comment]
Thanks for the report @DougLefelhocz 
Due to the limited details here, it's likely this relates to a broader bug currently in the game.
Please see https://trello.com/c/khJ8EGfG/192-strange-map-interaction
If you have further information, please get in touch on our discord bug-discussion channel. :)
